import {useState} from 'react';
import {Modal} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {SlidersHorizontal,X} from 'lucide-react-native';
import {IconButton} from '../../components/IconButton';
import {View,Text,ScrollView} from 'react-native';
import {Button,styles} from '../../components/ui';
import {useSettings} from '../settings/SettingsProvider';
import type {VocabularyItem} from '../../services/vocabulary/repository';
import type {Filters} from '../../services/vocabulary/review';
export function WordFilters({words,value,onChange,disabled=false,bookChoices}:{words:VocabularyItem[];value:Filters;onChange:(value:Filters)=>void;disabled?:boolean;bookChoices?:{id:string;title:string}[]}){
 const [open,setOpen]=useState(false);
 const {colors}=useSettings();const books=bookChoices?bookChoices.map(b=>[b.id,b.title]):[...new Map(words.flatMap(w=>w.source_books??[{id:w.source_book_id,title:w.source_book_title}]).filter(b=>b.id).map(b=>[b.id!,b.title??'未命名书籍'])).entries()];
 return <View><View style={[styles.row,{justifyContent:'space-between'}]}><Text numberOfLines={2} style={{color:colors.muted,flex:1}}>{value.book==='all'?'全部书籍':books.find(([id])=>id===value.book)?.[1]??'来源已删除'} · {['全部熟悉度','不认识','模糊','熟悉','掌握'][value.familiarity+1]} · {{all:'全部',due:'到期',new:'新词'}[value.due]}</Text><IconButton icon={SlidersHorizontal} label="筛选生词" disabled={disabled} onPress={()=>setOpen(true)}/></View><Modal visible={open} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><View style={{flex:1,justifyContent:'flex-end',backgroundColor:'#0006'}}><SafeAreaView edges={['bottom']} style={{maxHeight:'80%',padding:20,backgroundColor:colors.background,borderTopLeftRadius:20,borderTopRightRadius:20}}><View style={[styles.row,{justifyContent:'space-between'}]}><Text style={{color:colors.text,fontSize:20}}>筛选</Text><IconButton icon={X} label="关闭筛选" onPress={()=>setOpen(false)}/></View><ScrollView><View style={{gap:16,paddingVertical:16}}><Text style={{color:colors.muted}}>词书与复习状态</Text><ScrollView horizontal><View style={styles.row}>{[['all','全部书籍'],...books,['deleted','来源已删除']].map(([id,label])=><Button key={id} label={label} primary={value.book===id} disabled={disabled} onPress={()=>onChange({...value,book:id})}/>)}</View></ScrollView><View style={[styles.row,{flexWrap:'wrap'}]}>{['全部熟悉度','不认识','模糊','熟悉','掌握'].map((label,i)=><Button key={label} label={label} primary={value.familiarity===i-1} disabled={disabled} onPress={()=>onChange({...value,familiarity:i-1})}/>)}</View><View style={styles.row}>{(['all','due','new'] as const).map((due,i)=><Button key={due} label={['全部','已到期','新词'][i]} primary={value.due===due} disabled={disabled} onPress={()=>onChange({...value,due})}/>)}</View><View style={styles.row}><Button label="重置" onPress={()=>onChange({book:'all',familiarity:-1,due:'all'})}/><Button label="完成" primary onPress={()=>setOpen(false)}/></View></View></ScrollView></SafeAreaView></View></Modal></View>;
}
