import React,{useEffect} from 'react';
import {View} from 'react-native';
export const router={push:(route:any)=>window.dispatchEvent(new CustomEvent('preview-route',{detail:typeof route==='string'?route:route.pathname})),replace:(route:any)=>router.push(route)};
export const useFocusEffect=(fn:any)=>useEffect(fn,[fn]);
export const SafeAreaView=({children,style}:any)=><View style={[{flex:1},style]}>{children}</View>;
const books=[{id:'one',title:'The Secret Garden',format:'epub',progress:.1234,last_read_at:Date.now(),file_name:'sample.epub'},{id:'two',title:'Letters from a Quiet Station',format:'txt',progress:.0056,last_read_at:0,file_name:'sample.txt'}];
const words=['reluctant','vampire','contemptuous'].map((word,i)=>({word,lemma:word,translation:['adj. 不情愿的','n. 吸血鬼','adj. 轻蔑的'][i],phonetic:'',source_text:'She found herself strangely reluctant to leave.',source_book_id:'one',source_book_title:'The Secret Garden',lookup_count:2,familiarity:i,due_at:0,created_at:Date.now()}));
const db:any={getFirstAsync:async(sql:string)=>sql.includes('review_log')?{attempts:4,correct:3,words:3,newWords:2,reviewWords:1}:sql.includes('count(')?{n:3}:null,getAllAsync:async(sql:string)=>sql.includes('vocabulary')?words:sql.includes('books')?books:[],runAsync:async()=>({changes:1}),withExclusiveTransactionAsync:async(fn:any)=>fn(db)};
export const useSQLiteContext=()=>db;
export const cleanDeletedBookFiles=async()=>0;
export const importBook=async()=>null;
export const addSample=async()=> 'one';
export const exportAnki=async()=>{};
export const exportReadingDiagnostics=async()=>{};
export const volumeKeysAvailable=true;
export const readingSummary=async()=>({days:[],checkins:[]});
export const defaultAIConfig={baseUrl:'https://api.deepseek.com',model:'deepseek-chat'};
export const loadAIConfig=async()=>({apiKey:'',config:defaultAIConfig});
export const saveAIConfig=async()=>{};
